config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :farms do
    resources :lots do 
      resources :grooves do 
        post 'plague_reports/find', to: 'plague_reports#find_reports', as: 'find'
        resources :plague_reports 
      end
    end  
  end

  post '/grooves/:groofe_id/reports', to: 'plague_reports#create'
  post '/plague_reports/',to: 'plague_reports#create'
  # resources :nodes do
  #   resources :sensors
  #   delete "/sensors/:id", to: "sensors#destroy", as:"delete_sensor"
  #   post "/sensors", to: "sensors#create", as:"create_sensor"
   
  #   get '/sensors/:sensor_id/values', to: 'sensors#values', as: 'values'
  # end

  # post '/sensors/:id/values', to: 'sensors#create_value'
  root to: "farms#index"
end

app/models/farm.rb
class Farm < ApplicationRecord
    has_many :lots, dependent: :destroy
    belongs_to :user
    validates :name, presence: true
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  # GET /farms
  # GET /farms.json
  def index
    @farms = current_user.farms
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = current_user.farms.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to farms_path, notice: 'Cultivo creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      params.require(:farm).permit(:name)
    end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<%= form_with(model: farm, local: true) do |form| %>
  <% if farm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

      <ul>
      <% farm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Nombre del cultivo" %>
    <%= form.text_field :name, id: :farm_name,class:"form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Aceptar", {class:'btn btn-success right-button'} %>
  </div>

<% end %>

app/views/farms/edit.html.erb
<div class="center">
    <h1>Editar Cultivo</h1>

    <%= render 'form', farm: @farm %>

    <%= link_to 'Show', @farm %> |
    <%= link_to 'Back', farms_path %>
</div>

app/views/farms/index.html.erb
<div class="center">
  <p id="notice"><%= notice %></p>
  <h1>Cultivos</h1>
  <%= link_to 'Crear Cultivo', new_farm_path, {style:'color:#FFFFFF;',class:'btn btn-success right-button'} %>
  
  <% if current_user.farms.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Identificador</th>
          <th>Nombre</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @farms.each do |farm| %>
          <tr>
            <td ><%= farm.id %></td>
            <td><%= farm.name %></td>
            <td><%= link_to 'Ver lotes', farm_lots_path(farm.id) %> </td>
            <td><%= link_to 'Editar', edit_farm_path(farm) %></td>
            <td><%= link_to 'Eliminar', farm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%else%>
    <p class="left">Usted no ha creado ningún cultivo todavía, para hacerlo haga clic en "Crear Cultivo".</p>
  <%end%>
    
</div>
<br>

app/views/farms/new.html.erb
<div class="center">
    <h1>Nuevo Cultivo</h1>
    <%= render 'form', farm: @farm %>
    <%= link_to 'Volver', farms_path, {class:'btn btn-danger right-button'}%>
</div>

app/views/farms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <p>
    <strong>Name:</strong>
    <%= @farm.name %>
  </p>

  <%= link_to 'Ver lotes', farm_lots_path(@farm.id) %> 

  <%= link_to 'Edit', edit_farm_path(@farm) %> |
  <%= link_to 'Back', farms_path %>
</div>