config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :farms do
    resources :lots do 
      resources :grooves do 
        post 'plague_reports/find', to: 'plague_reports#find_reports', as: 'find'
        resources :plague_reports 
      end
    end  
  end

  post '/grooves/:groofe_id/reports', to: 'plague_reports#create'
  post '/plague_reports/',to: 'plague_reports#create'
  # resources :nodes do
  #   resources :sensors
  #   delete "/sensors/:id", to: "sensors#destroy", as:"delete_sensor"
  #   post "/sensors", to: "sensors#create", as:"create_sensor"
   
  #   get '/sensors/:sensor_id/values', to: 'sensors#values', as: 'values'
  # end

  # post '/sensors/:id/values', to: 'sensors#create_value'
  root to: "farms#index"
end

app/models/plague_report.rb
class PlagueReport < ApplicationRecord
  belongs_to :groove
  has_many :sick_plants
end

app/controllers/plague_reports_controller.rb
class PlagueReportsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_groove, only: [:create, :index,:show,:find_reports]
  before_action :set_plague_report, only: [:show]
  before_action :set_plague_report_by_date, only: [:create]
  before_action :set_user, only: [:create]

  def create
    # validar que location <= quantity
    if @plague_report.blank?
      p "No hay reporte en esa fecha, creando uno..."
      @plague_report = @groove.plague_reports.new(plague_reports_params)    
      if @plague_report.save
        p "Operación realizada en plague reports"
        sick_plant = @plague_report.sick_plants.create(sick_plant_params)
      else
        p "Error realizando operación create en plague reports"
      end
    else
      p "Reporte encontrado"  
      sick_plant = @plague_report.sick_plants.create(sick_plant_params)
    end
    send_alert
  end

  def index
    @initial_date = Date.today
    @final_date = Date.today
    @plague_reports = @groove.plague_reports
    column_chart_data(@plague_reports)
  end

  def column_chart_data(reports)
    gon.column_chart_data = reports.map { |a| [a.reportDate,a.sick_plants.count] } 
  end

  def show
    p @sick_plants_l = @plague_report.sick_plants.pluck(:location).join(",")
    quantity = @groove.quantity
    
    # pie chart
    sick_plants_n = @plague_report.sick_plants.count
    healthy_plants_n = quantity-sick_plants_n
    gon.graphic_data = [
      ['Estado','Cantidad'],
      ['Sanas',healthy_plants_n],
      ['Enfermas',sick_plants_n]
    ]

    data = []
    (0..quantity-1).each_with_index do |i|
      data.push([i,0,0])
    end
    print data

    @plague_report.sick_plants.each do |plant|
      data[plant.location] = [plant.location,0,1]
    end
    
    # heatline chart
    gon.heatline_data = data
  end
  
  def send_alert
    ReportMailer.sample_email('msierr37@eafit.edu.co').deliver
        # format.html { redirect_to farm_lot_, notice: 'Hay una plaga en el cultivo' }
        #format.json { render :show, status: :created, location: @user }
  end
  
  def find_reports
    dates = params[:dates]
    @initial_date = params[:dates][:initial_date]
    @final_date = params[:dates][:final_date]

    if @final_date < @initial_date
      redirect_to farm_lot_groofe_plague_reports_path, notice: 'La fecha final debe ser mayor o igual a la fecha inicial.' 
    else
      p "hola"
      @plague_reports = @groove.plague_reports.where(reportDate: @initial_date..@final_date)
      p " resultado #{@plague_reports.count}"
      p "hola"
      column_chart_data(@plague_reports)
      # redirect_to farm_lot_groofe_plague_reports_path(groofe_id: @groove.id), notice: 'Busqueda realizada.' 
      
      # redirect_to :back
    end
  end

  private

  def plague_reports_params
    params.require(:plague_report).permit(:reportDate)
  end

  def sick_plant_params
    params.require(:sick_plant).permit(:location)
  end

  def set_user
    @user = Farm.find(params[:farm_id]).user
  end
  
  def set_plague_report
    @plague_report = PlagueReport.find(params[:id])
  end

  def set_plague_report_by_date
    @plague_report = @groove.plague_reports.find_by(reportDate: plague_reports_params[:reportDate])
  end

  
  def set_groove
    @groove = Groove.find(params[:groofe_id])
  end
end

app/helpers/plague_reports_helper.rb
module PlagueReportsHelper
end

app/views/plague_reports/_form.html.erb
<%= form_with(url:   farm_lot_groofe_find_path, local: true) do |form| %>
  <h3>Buscar Reporte</h3>
  <div class="field">
    <%= form.label :fecha_inicial %>
    <%= date_field :dates,:initial_date,value:@initial_date, class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :fecha_final %>
    <%= date_field :dates,:final_date,value:@final_date, class:"form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Buscar",style:'color:#FFFFFF;',class:'btn btn-success left' %>
  </div>
   <%= link_to 'Volver', farm_lot_grooves_path , {style:'color:#FFFFFF;',class:'btn btn-danger'} %>
<% end %>

app/views/plague_reports/_heatline_chart.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/heatmap.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>


<div id="container1" style="height: 400px; min-width: 600px; max-width: 800px; margin: 0 auto"></div>
<script type="text/javascript">
    Highcharts.chart('container1', {

    chart: {
        type: 'heatmap',
        marginTop: 40,
        marginBottom: 80,
        plotBorderWidth: 1
    },


    title: {
        text: 'Mapa de calor surco con Ubicación'
    },

    colorAxis: {
        min: 0,
        minColor: '#31B404',
        maxColor: '#8A0808'
    },

    legend: {
        align: 'right',
        layout: 'vertical',
        margin: 0,
        verticalAlign: 'top',
        y: 25,
        symbolHeight: 280
    },

    tooltip: {
        formatter: function () {
        return '<b>' + this.series.xAxis.categories[this.point.x] + '</b> sold <br><b>' +
            this.point.value + '</b> items on <br><b>' + this.series.yAxis.categories[this.point.y] + '</b>';
        }
    },

    series: [{
        name: 'Mapa de calor surco con ubicación',
        borderWidth: 1,
        data: gon.heatline_data,
        dataLabels: {
        enabled: true,
        color: '#FFFFFF'
        }
    }]

    });
</script>

app/views/plague_reports/create.html.erb
<h1>PlagueReports#create</h1>
<p>Find me in app/views/plague_reports/create.html.erb</p>

app/views/plague_reports/find_reports.html.erb
<div class="center">
  <%= render 'form', plague_report: @plague_report %>
  
  <%if @plague_reports.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Cantidad de plagas</th>
          
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @plague_reports.each do |report| %>
          <tr>
            <td><%= report.reportDate %></td>
            <td><%= report.sick_plants.count %></td>
            <td><%= link_to 'Mostrar', farm_lot_groofe_plague_report_path(id: report.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= render 'graphics/column_chart', plague_report: @plague_report %>
  <%else%>
    </br>
    <h2 class="center">No se encontró ningun reporte entre <%=@initial_date%> 
      y <%=@final_date%></h2>
  <%end%>
</div>

app/views/plague_reports/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <h1>Reportes de Plagas del Surco <%= @groove.id %></h1>
    <%= render 'form', plague_report: @plague_report %>
    <div class="center">
      <%if @plague_reports.present? %>
        <%= render 'graphics/column_chart', plague_report: @plague_report %>
      <%else%>
        </br>
        <h2 class="center">No se hallaron hay reportes en este surco</h2>
      <%end %>
    </div>
</div>

app/views/plague_reports/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
  <h3>Reporte del día <%= @plague_report.reportDate %></h3>
  <p>
    <strong>Descripción:</strong>
    El surco <%=@plague_report.groove.id%> en el dia,  <%= @plague_report.reportDate %>
    presentó un total de <%= @plague_report.sick_plants.count%> plantas afectadas.
    <br>
    <strong>La posición de de las plantas afectadas en este surco es:</strong> 
    <%= @sick_plants_l %>
  </p>

  <%= link_to 'Atrás', farm_lot_groofe_plague_reports_path , {style:'color:#FFFFFF;',class:'btn btn-danger left'} %>
  <br>
  <div>
    <div class="left"><%= render 'graphics/heatline_chart' %></div>
    <div class="right"><%= render 'graphics/pie_chart' %></div>
  </div>
</div>