config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :farms do
    resources :lots do 
      resources :grooves do 
        post 'plague_reports/find', to: 'plague_reports#find_reports', as: 'find'
        resources :plague_reports 
      end
    end  
  end

  post '/grooves/:groofe_id/reports', to: 'plague_reports#create'
  post '/plague_reports/',to: 'plague_reports#create'
  # resources :nodes do
  #   resources :sensors
  #   delete "/sensors/:id", to: "sensors#destroy", as:"delete_sensor"
  #   post "/sensors", to: "sensors#create", as:"create_sensor"
   
  #   get '/sensors/:sensor_id/values', to: 'sensors#values', as: 'values'
  # end

  # post '/sensors/:id/values', to: 'sensors#create_value'
  root to: "farms#index"
end

app/models/lot.rb
class Lot < ApplicationRecord
  belongs_to :farm
  has_many :grooves, dependent: :destroy
  validates :name, presence: true
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lot, only: [:show, :edit, :update, :destroy]
  before_action :set_farm, only: [:new,:index]
  # GET /lots
  # GET /lots.json
  def index
    @lots = @farm.lots
  end

  # GET /lots/1
  # GET /lots/1.json
  def show
  end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit
  end

  # POST /lots
  # POST /lots.json
  def create
    @lot = Lot.new(lot_params)
    loop do
      @lot.key = ([*('a'..'z'),*('A'..'Z'),*('0'..'9')]-%w()).sample(8).join
      break unless Lot.exists?(key: @lot.key)
    end

    respond_to do |format|
      if @lot.save
        format.html { redirect_to farm_lots_path, notice: 'Lote creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1
  # PATCH/PUT /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1
  # DELETE /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lot
      @lot = Lot.find(params[:id])
    end

    def set_farm
      @farm = Farm.find(params[:farm_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lot_params
      params.require(:lot).permit(:name, :location, :farm_id)
    end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_with(url: farm_lots_path, local: true) do |form| %>
  <% if lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
      <% lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name,"Nombre del lote" %>
    <%= text_field :lot,:name, id: :lot_name,class:"form-control"%>
  </div>

  <div class="field">
    <%= form.label :location,"Ubicación"%>
    <%= text_field :lot,:location, id: :lot_location,class:"form-control" %>
  </div>

  <div class="field">
    <%= hidden_field(:lot, :farm_id, value: @farm.id) %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Aceptar", {class:'btn btn-success right-button'} %>
  </div>
<% end %>

app/views/lots/edit.html.erb
<h1>Editing Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Mostrar', farm_lot_path %> |
<%= link_to 'Volver', farm_lots_path %>

app/views/lots/index.html.erb
<div class="center">
  <p id="notice"><%= notice %></p>

  <h2>Lotes del cultivo: <%= @farm.name%></h2>
  <h4>Identificador del cultivo: <%= @farm.id%></h4>

  <%= link_to 'Crear lote', new_farm_lot_path, {style:'color:#FFFFFF;',class:'btn btn-success right-button'} %>
  <%= link_to 'Volver', farms_path , {style:'color:#FFFFFF;',class:'btn btn-danger right-button'} %>
  <% if @lots.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Identificador</th>
          <th>Nombre</th>
          <th>Ubicación</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @lots.each do |lot| %>
          <tr>
            <td><%= lot.id %></td>
            <td><%= lot.name %></td>
            <td><%= lot.location %></td>
            <td><%= link_to 'Ver surcos', farm_lot_grooves_path(lot_id: lot.id) %> </td>
            <td><%= link_to 'Editar', edit_farm_lot_path(id: lot.id) %></td>
            <td><%= link_to 'Eliminar', controller: "lots", method: "delete", data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%else%>
    <p class="left">Usted no ha creado ningun lote para este cultivo,
     para hacerlo haga clic en "Crear Lote".</p>
  <%end%>
  
  <br>
<div class="center">

app/views/lots/new.html.erb
<div class="center">
    <h1>Nuevo Lote</h1>
    <%= render 'form', lot: @lot %>
    <%= link_to 'Volver', farm_lots_path, {class:'btn btn-danger right-button'}%>
</div>

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @lot.name %>
</p>

<p>
  <strong>Ubicación:</strong>
  <%= @lot.location %>
</p>

<p>
  <strong>Cultivo:</strong>
  <%= @lot.farm.name %>
</p>

<%= link_to 'Ver surcos', farm_lot_grooves_path(lot_id: @lot.id) %> 

<%= link_to 'Editar', edit_farm_lot_path(@lot) %> |
<%= link_to 'Volver', farm_lots_path %>