config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :farms do
    resources :lots do 
      resources :grooves do 
        post 'plague_reports/find', to: 'plague_reports#find_reports', as: 'find'
        resources :plague_reports 
      end
    end  
  end

  post '/grooves/:groofe_id/reports', to: 'plague_reports#create'
  post '/plague_reports/',to: 'plague_reports#create'
  # resources :nodes do
  #   resources :sensors
  #   delete "/sensors/:id", to: "sensors#destroy", as:"delete_sensor"
  #   post "/sensors", to: "sensors#create", as:"create_sensor"
   
  #   get '/sensors/:sensor_id/values', to: 'sensors#values', as: 'values'
  # end

  # post '/sensors/:id/values', to: 'sensors#create_value'
  root to: "farms#index"
end

app/models/groove.rb
class Groove < ApplicationRecord
  belongs_to :lot
  has_many :plague_reports, dependent: :destroy
  validates :quantity,numericality: {greater_than: 0}
end

app/controllers/grooves_controller.rb
class GroovesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_groofe, only: [:show, :edit, :update, :destroy]
  before_action :set_lot, only: [:new,:index]
  # GET /grooves
  # GET /grooves.json
  def index
    @grooves = Groove.where(lot_id: @lot.id)
    grooves_n = @grooves.count
    @show_lot = false
    data = []
    
    @grooves.each_with_index do |groove,i|
      if groove.plague_reports.present?
        @show_lot = true
        sick_plants = groove.plague_reports.last.sick_plants.pluck(:location)
        (0..groove.quantity-1).each do |j|
          if sick_plants.include?(j)
            data.push([j,i,1])  
          else
            data.push([j,i,0])
          end
        end
      end
    end
    gon.heatline_data = data
  end
  # GET /grooves/1
  # GET /grooves/1.json
  def show
  end

  # GET /grooves/new
  def new
    @groofe = Groove.new
  end

  # GET /grooves/1/edit
  def edit
  end

  # POST /grooves
  # POST /grooves.json
  def create
    @groofe = Groove.new(groofe_params)

    respond_to do |format|
      if @groofe.save
        format.html { redirect_to  farm_lot_grooves_path, notice: 'Groove was successfully created.' }
        format.json { render :show, status: :created, location: @groofe }
      else
        format.html { render :new }
        format.json { render json: @groofe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grooves/1
  # PATCH/PUT /grooves/1.json
  def update
    respond_to do |format|
      if @groofe.update(groofe_params)
        format.html { redirect_to @groofe, notice: 'Groove was successfully updated.' }
        format.json { render :show, status: :ok, location: @groofe }
      else
        format.html { render :edit }
        format.json { render json: @groofe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grooves/1
  # DELETE /grooves/1.json
  def destroy
    @groofe.destroy
    respond_to do |format|
      format.html { redirect_to grooves_url, notice: 'Groove was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_groofe
      @groofe = Groove.find(params[:id])
    end

    def set_lot
      @lot = Lot.find(params[:lot_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def groofe_params
      params.require(:groofe).permit(:quantity, :lot_id)
    end
end

app/helpers/grooves_helper.rb
module GroovesHelper
end

app/views/grooves/_form.html.erb
<%= form_with(url: farm_lot_grooves_path, local: true) do |form| %>
  <% if groofe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(groofe.errors.count, "error") %> prohibited this groofe from being saved:</h2>

      <ul>
      <% groofe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity, "Cantidad de plantas en el surco" %>
    <%= number_field :groofe,:quantity, id: :groofe_quantity,class:"form-control" %>
  </div>

  <div class="field">
    <%= hidden_field(:groofe, :lot_id, value: @lot.id) %>
  </div>
  <br>
  
  <div class="actions">
    <%= form.submit "Aceptar", {class:'btn btn-success right-button'} %>
  </div>
<% end %>

app/views/grooves/edit.html.erb
<h1>Editing Groofe</h1>

<%= render 'form', groofe: @groofe %>

<%= link_to 'Mostrar', @groofe %> |
<%= link_to 'Volver', grooves_path %>

app/views/grooves/index.html.erb
<div class="center">
  <p id="notice"><%= notice %></p>

  <h2>Surcos del lote: <%= @lot.name%></h2>
  <h4>Identificador del lote: <%= @lot.id%></h4>

  <%= link_to 'Crear surco', new_farm_lot_groofe_path, {style:'color:#FFFFFF;',class:'btn btn-success right-button'} %>
  <%= link_to 'Volver', farm_lots_path , {style:'color:#FFFFFF;',class:'btn btn-danger right-button'} %>
  <% if @grooves.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Identificador</th>
          <th>Cantidad de plantas</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @grooves.each do |groofe| %>
          <tr>
            <td><%= groofe.id %></td>
            <td><%= groofe.quantity %></td>
            <td><%= link_to 'Ver reportes', farm_lot_groofe_plague_reports_path(groofe_id: groofe.id) %></td> 
            <td><%= link_to 'Editar', edit_farm_lot_groofe_path(id: groofe.id) %></td>
            <td><%= link_to 'Eliminar', controller: "grooves", method: "destroy", data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%if @show_lot%>
      <%= render 'graphics/heatline_chart' %>
    <%end%>
  <%else%>
    <p class="left">Usted no ha creado todavía ningun surco para este lote,
     para hacerlo haga clic en "Crear Surco".</p>
  <%end%>
  <br>
</div>

app/views/grooves/new.html.erb
<div class="center">    
    <h1>Nuevo surco</h1>
    <%= render 'form', groofe: @groofe %>
    <%= link_to 'Volver', farm_lot_grooves_path, {class:'btn btn-danger right-button'}%>
<div>

app/views/grooves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @groofe.quantity %>
</p>

<p>
  <strong>Lot:</strong>
  <%= @groofe.lot %>
</p>

<%= link_to 'Editar', edit_groofe_path(@groofe) %> |
<%= link_to 'Volver', grooves_path %>